services:
  - type: web
    name: smart-ats-api
    env: python
    buildCommand: ./build.sh
    startCommand: python -m uvicorn src.api.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    plan: free
    pythonVersion: 3.9
