services:
  - type: web
    name: smart-ats-api
    env: python
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install "fastapi<0.69.0" "uvicorn<0.15.0" "pydantic<1.9.0" "starlette<0.15.0" google-generativeai python-multipart PyPDF2 python-dotenv
    startCommand: python simple_app.py $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    plan: free
    pythonVersion: 3.8.17
